#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capa_datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="colitas_felices_2")]
	public partial class ColitasFelicesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCuenta(Cuenta instance);
    partial void UpdateCuenta(Cuenta instance);
    partial void DeleteCuenta(Cuenta instance);
    partial void InsertPerfil(Perfil instance);
    partial void UpdatePerfil(Perfil instance);
    partial void DeletePerfil(Perfil instance);
    partial void InsertProveedorExterno(ProveedorExterno instance);
    partial void UpdateProveedorExterno(ProveedorExterno instance);
    partial void DeleteProveedorExterno(ProveedorExterno instance);
    #endregion
		
		public ColitasFelicesDataContext() : 
				base(global::capa_datos.Properties.Settings.Default.colitas_felices_2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ColitasFelicesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ColitasFelicesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ColitasFelicesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ColitasFelicesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cuenta> Cuenta
		{
			get
			{
				return this.GetTable<Cuenta>();
			}
		}
		
		public System.Data.Linq.Table<Perfil> Perfil
		{
			get
			{
				return this.GetTable<Perfil>();
			}
		}
		
		public System.Data.Linq.Table<ProveedorExterno> ProveedorExterno
		{
			get
			{
				return this.GetTable<ProveedorExterno>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CrearUsuario_Admin")]
		public int SP_CrearUsuario_Admin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(150)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(255)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rol", DbType="TinyInt")] System.Nullable<byte> rol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(15)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(100)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(100)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(15)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(255)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FotoPerfil", DbType="VarBinary(MAX)")] System.Data.Linq.Binary fotoPerfil, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuentaID", DbType="Int")] ref System.Nullable<int> cuentaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PerfilID", DbType="Int")] ref System.Nullable<int> perfilID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Exitoso", DbType="Bit")] ref System.Nullable<bool> exitoso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mensaje", DbType="VarChar(500)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, password, rol, cedula, nombres, apellidos, telefono, direccion, fotoPerfil, cuentaID, perfilID, exitoso, mensaje);
			cuentaID = ((System.Nullable<int>)(result.GetParameterValue(9)));
			perfilID = ((System.Nullable<int>)(result.GetParameterValue(10)));
			exitoso = ((System.Nullable<bool>)(result.GetParameterValue(11)));
			mensaje = ((string)(result.GetParameterValue(12)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VerificarLogin")]
		public int SP_VerificarLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(150)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(255)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoginExitoso", DbType="Bit")] ref System.Nullable<bool> loginExitoso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuentaID", DbType="Int")] ref System.Nullable<int> cuentaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RolUsuario", DbType="TinyInt")] ref System.Nullable<byte> rolUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mensaje", DbType="VarChar(500)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, password, loginExitoso, cuentaID, rolUsuario, mensaje);
			loginExitoso = ((System.Nullable<bool>)(result.GetParameterValue(2)));
			cuentaID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			rolUsuario = ((System.Nullable<byte>)(result.GetParameterValue(4)));
			mensaje = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CambiarEstadoCuenta")]
		public int SP_CambiarEstadoCuenta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuentaID", DbType="Int")] System.Nullable<int> cuentaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoEstado", DbType="TinyInt")] System.Nullable<byte> nuevoEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resultado", DbType="Bit")] ref System.Nullable<bool> resultado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="TinyInt")] ref System.Nullable<byte> codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mensaje", DbType="NVarChar(300)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuentaID, nuevoEstado, resultado, codigo, mensaje);
			resultado = ((System.Nullable<bool>)(result.GetParameterValue(2)));
			codigo = ((System.Nullable<byte>)(result.GetParameterValue(3)));
			mensaje = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Cuenta_Buscar")]
		public ISingleResult<sp_Cuenta_BuscarResult> sp_Cuenta_Buscar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Termino", DbType="VarChar(100)")] string termino)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), termino);
			return ((ISingleResult<sp_Cuenta_BuscarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LoginGoogle")]
		public int SP_LoginGoogle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GoogleID", DbType="VarChar(255)")] string googleID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(150)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuentaID", DbType="Int")] ref System.Nullable<int> cuentaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RolUsuario", DbType="TinyInt")] ref System.Nullable<byte> rolUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequiereCompletarPerfil", DbType="Bit")] ref System.Nullable<bool> requiereCompletarPerfil, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EsNuevoUsuario", DbType="Bit")] ref System.Nullable<bool> esNuevoUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Exitoso", DbType="Bit")] ref System.Nullable<bool> exitoso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mensaje", DbType="VarChar(500)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), googleID, email, nombre, cuentaID, rolUsuario, requiereCompletarPerfil, esNuevoUsuario, exitoso, mensaje);
			cuentaID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			rolUsuario = ((System.Nullable<byte>)(result.GetParameterValue(4)));
			requiereCompletarPerfil = ((System.Nullable<bool>)(result.GetParameterValue(5)));
			esNuevoUsuario = ((System.Nullable<bool>)(result.GetParameterValue(6)));
			exitoso = ((System.Nullable<bool>)(result.GetParameterValue(7)));
			mensaje = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarCuenta")]
		public int SP_EliminarCuenta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuentaID", DbType="Int")] System.Nullable<int> cuentaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Exitoso", DbType="Bit")] ref System.Nullable<bool> exitoso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mensaje", DbType="VarChar(500)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuentaID, exitoso, mensaje);
			exitoso = ((System.Nullable<bool>)(result.GetParameterValue(1)));
			mensaje = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CambiarRol")]
		public int SP_CambiarRol([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuentaID", DbType="Int")] System.Nullable<int> cuentaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoRol", DbType="TinyInt")] System.Nullable<byte> nuevoRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Exitoso", DbType="Bit")] ref System.Nullable<bool> exitoso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mensaje", DbType="VarChar(500)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuentaID, nuevoRol, exitoso, mensaje);
			exitoso = ((System.Nullable<bool>)(result.GetParameterValue(2)));
			mensaje = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarPerfil")]
		public int SP_ActualizarPerfil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PerfilID", DbType="Int")] System.Nullable<int> perfilID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(15)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(100)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(100)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(15)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(255)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FotoPerfil", DbType="VarBinary(MAX)")] System.Data.Linq.Binary fotoPerfil, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Exitoso", DbType="Bit")] ref System.Nullable<bool> exitoso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mensaje", DbType="VarChar(500)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), perfilID, cedula, nombres, apellidos, telefono, direccion, fotoPerfil, exitoso, mensaje);
			exitoso = ((System.Nullable<bool>)(result.GetParameterValue(7)));
			mensaje = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CambiarPassword")]
		public int SP_CambiarPassword([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuentaID", DbType="Int")] System.Nullable<int> cuentaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoPassword", DbType="VarChar(255)")] string nuevoPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Exitoso", DbType="Bit")] ref System.Nullable<bool> exitoso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mensaje", DbType="VarChar(500)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuentaID, nuevoPassword, exitoso, mensaje);
			exitoso = ((System.Nullable<bool>)(result.GetParameterValue(2)));
			mensaje = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cuenta")]
	public partial class Cuenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CuentaID;
		
		private string _Email;
		
		private System.Data.Linq.Binary _Password;
		
		private byte _Rol;
		
		private System.DateTime _FechaRegistro;
		
		private System.Nullable<System.DateTime> _UltimoAcceso;
		
		private int _IntentosFallidos;
		
		private System.Nullable<System.DateTime> _BloqueadoHasta;
		
		private int _VecesBloqueo;
		
		private string _TokenRecuperacion;
		
		private System.Nullable<System.DateTime> _TokenExpiracion;
		
		private string _ClaveTemporal;
		
		private System.Nullable<System.DateTime> _ClaveTemporalExpira;
		
		private string _TipoAutenticacion;
		
		private byte _Estado;
		
		private EntitySet<Perfil> _Perfil;
		
		private EntitySet<ProveedorExterno> _ProveedorExterno;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCuentaIDChanging(int value);
    partial void OnCuentaIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(System.Data.Linq.Binary value);
    partial void OnPasswordChanged();
    partial void OnRolChanging(byte value);
    partial void OnRolChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    partial void OnUltimoAccesoChanging(System.Nullable<System.DateTime> value);
    partial void OnUltimoAccesoChanged();
    partial void OnIntentosFallidosChanging(int value);
    partial void OnIntentosFallidosChanged();
    partial void OnBloqueadoHastaChanging(System.Nullable<System.DateTime> value);
    partial void OnBloqueadoHastaChanged();
    partial void OnVecesBloqueoChanging(int value);
    partial void OnVecesBloqueoChanged();
    partial void OnTokenRecuperacionChanging(string value);
    partial void OnTokenRecuperacionChanged();
    partial void OnTokenExpiracionChanging(System.Nullable<System.DateTime> value);
    partial void OnTokenExpiracionChanged();
    partial void OnClaveTemporalChanging(string value);
    partial void OnClaveTemporalChanged();
    partial void OnClaveTemporalExpiraChanging(System.Nullable<System.DateTime> value);
    partial void OnClaveTemporalExpiraChanged();
    partial void OnTipoAutenticacionChanging(string value);
    partial void OnTipoAutenticacionChanged();
    partial void OnEstadoChanging(byte value);
    partial void OnEstadoChanged();
    #endregion
		
		public Cuenta()
		{
			this._Perfil = new EntitySet<Perfil>(new Action<Perfil>(this.attach_Perfil), new Action<Perfil>(this.detach_Perfil));
			this._ProveedorExterno = new EntitySet<ProveedorExterno>(new Action<ProveedorExterno>(this.attach_ProveedorExterno), new Action<ProveedorExterno>(this.detach_ProveedorExterno));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CuentaID
		{
			get
			{
				return this._CuentaID;
			}
			set
			{
				if ((this._CuentaID != value))
				{
					this.OnCuentaIDChanging(value);
					this.SendPropertyChanging();
					this._CuentaID = value;
					this.SendPropertyChanged("CuentaID");
					this.OnCuentaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarBinary(500)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="TinyInt NOT NULL")]
		public byte Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimoAcceso", DbType="DateTime")]
		public System.Nullable<System.DateTime> UltimoAcceso
		{
			get
			{
				return this._UltimoAcceso;
			}
			set
			{
				if ((this._UltimoAcceso != value))
				{
					this.OnUltimoAccesoChanging(value);
					this.SendPropertyChanging();
					this._UltimoAcceso = value;
					this.SendPropertyChanged("UltimoAcceso");
					this.OnUltimoAccesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntentosFallidos", DbType="Int NOT NULL")]
		public int IntentosFallidos
		{
			get
			{
				return this._IntentosFallidos;
			}
			set
			{
				if ((this._IntentosFallidos != value))
				{
					this.OnIntentosFallidosChanging(value);
					this.SendPropertyChanging();
					this._IntentosFallidos = value;
					this.SendPropertyChanged("IntentosFallidos");
					this.OnIntentosFallidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloqueadoHasta", DbType="DateTime")]
		public System.Nullable<System.DateTime> BloqueadoHasta
		{
			get
			{
				return this._BloqueadoHasta;
			}
			set
			{
				if ((this._BloqueadoHasta != value))
				{
					this.OnBloqueadoHastaChanging(value);
					this.SendPropertyChanging();
					this._BloqueadoHasta = value;
					this.SendPropertyChanged("BloqueadoHasta");
					this.OnBloqueadoHastaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VecesBloqueo", DbType="Int NOT NULL")]
		public int VecesBloqueo
		{
			get
			{
				return this._VecesBloqueo;
			}
			set
			{
				if ((this._VecesBloqueo != value))
				{
					this.OnVecesBloqueoChanging(value);
					this.SendPropertyChanging();
					this._VecesBloqueo = value;
					this.SendPropertyChanged("VecesBloqueo");
					this.OnVecesBloqueoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TokenRecuperacion", DbType="VarChar(255)")]
		public string TokenRecuperacion
		{
			get
			{
				return this._TokenRecuperacion;
			}
			set
			{
				if ((this._TokenRecuperacion != value))
				{
					this.OnTokenRecuperacionChanging(value);
					this.SendPropertyChanging();
					this._TokenRecuperacion = value;
					this.SendPropertyChanged("TokenRecuperacion");
					this.OnTokenRecuperacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TokenExpiracion", DbType="DateTime")]
		public System.Nullable<System.DateTime> TokenExpiracion
		{
			get
			{
				return this._TokenExpiracion;
			}
			set
			{
				if ((this._TokenExpiracion != value))
				{
					this.OnTokenExpiracionChanging(value);
					this.SendPropertyChanging();
					this._TokenExpiracion = value;
					this.SendPropertyChanged("TokenExpiracion");
					this.OnTokenExpiracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaveTemporal", DbType="VarChar(255)")]
		public string ClaveTemporal
		{
			get
			{
				return this._ClaveTemporal;
			}
			set
			{
				if ((this._ClaveTemporal != value))
				{
					this.OnClaveTemporalChanging(value);
					this.SendPropertyChanging();
					this._ClaveTemporal = value;
					this.SendPropertyChanged("ClaveTemporal");
					this.OnClaveTemporalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaveTemporalExpira", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClaveTemporalExpira
		{
			get
			{
				return this._ClaveTemporalExpira;
			}
			set
			{
				if ((this._ClaveTemporalExpira != value))
				{
					this.OnClaveTemporalExpiraChanging(value);
					this.SendPropertyChanging();
					this._ClaveTemporalExpira = value;
					this.SendPropertyChanged("ClaveTemporalExpira");
					this.OnClaveTemporalExpiraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoAutenticacion", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TipoAutenticacion
		{
			get
			{
				return this._TipoAutenticacion;
			}
			set
			{
				if ((this._TipoAutenticacion != value))
				{
					this.OnTipoAutenticacionChanging(value);
					this.SendPropertyChanging();
					this._TipoAutenticacion = value;
					this.SendPropertyChanged("TipoAutenticacion");
					this.OnTipoAutenticacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt NOT NULL")]
		public byte Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cuenta_Perfil", Storage="_Perfil", ThisKey="CuentaID", OtherKey="CuentaID")]
		public EntitySet<Perfil> Perfil
		{
			get
			{
				return this._Perfil;
			}
			set
			{
				this._Perfil.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cuenta_ProveedorExterno", Storage="_ProveedorExterno", ThisKey="CuentaID", OtherKey="CuentaID")]
		public EntitySet<ProveedorExterno> ProveedorExterno
		{
			get
			{
				return this._ProveedorExterno;
			}
			set
			{
				this._ProveedorExterno.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Perfil(Perfil entity)
		{
			this.SendPropertyChanging();
			entity.Cuenta = this;
		}
		
		private void detach_Perfil(Perfil entity)
		{
			this.SendPropertyChanging();
			entity.Cuenta = null;
		}
		
		private void attach_ProveedorExterno(ProveedorExterno entity)
		{
			this.SendPropertyChanging();
			entity.Cuenta = this;
		}
		
		private void detach_ProveedorExterno(ProveedorExterno entity)
		{
			this.SendPropertyChanging();
			entity.Cuenta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Perfil")]
	public partial class Perfil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PerfilID;
		
		private int _CuentaID;
		
		private string _Cedula;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _Telefono;
		
		private string _Direccion;
		
		private System.Data.Linq.Binary _FotoPerfil;
		
		private char _PerfilCompleto;
		
		private EntityRef<Cuenta> _Cuenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPerfilIDChanging(int value);
    partial void OnPerfilIDChanged();
    partial void OnCuentaIDChanging(int value);
    partial void OnCuentaIDChanged();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnFotoPerfilChanging(System.Data.Linq.Binary value);
    partial void OnFotoPerfilChanged();
    partial void OnPerfilCompletoChanging(char value);
    partial void OnPerfilCompletoChanged();
    #endregion
		
		public Perfil()
		{
			this._Cuenta = default(EntityRef<Cuenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerfilID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PerfilID
		{
			get
			{
				return this._PerfilID;
			}
			set
			{
				if ((this._PerfilID != value))
				{
					this.OnPerfilIDChanging(value);
					this.SendPropertyChanging();
					this._PerfilID = value;
					this.SendPropertyChanged("PerfilID");
					this.OnPerfilIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaID", DbType="Int NOT NULL")]
		public int CuentaID
		{
			get
			{
				return this._CuentaID;
			}
			set
			{
				if ((this._CuentaID != value))
				{
					if (this._Cuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCuentaIDChanging(value);
					this.SendPropertyChanging();
					this._CuentaID = value;
					this.SendPropertyChanged("CuentaID");
					this.OnCuentaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(15)")]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(100)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(100)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(255)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoPerfil", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FotoPerfil
		{
			get
			{
				return this._FotoPerfil;
			}
			set
			{
				if ((this._FotoPerfil != value))
				{
					this.OnFotoPerfilChanging(value);
					this.SendPropertyChanging();
					this._FotoPerfil = value;
					this.SendPropertyChanged("FotoPerfil");
					this.OnFotoPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerfilCompleto", DbType="Char(1) NOT NULL")]
		public char PerfilCompleto
		{
			get
			{
				return this._PerfilCompleto;
			}
			set
			{
				if ((this._PerfilCompleto != value))
				{
					this.OnPerfilCompletoChanging(value);
					this.SendPropertyChanging();
					this._PerfilCompleto = value;
					this.SendPropertyChanged("PerfilCompleto");
					this.OnPerfilCompletoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cuenta_Perfil", Storage="_Cuenta", ThisKey="CuentaID", OtherKey="CuentaID", IsForeignKey=true)]
		public Cuenta Cuenta
		{
			get
			{
				return this._Cuenta.Entity;
			}
			set
			{
				Cuenta previousValue = this._Cuenta.Entity;
				if (((previousValue != value) 
							|| (this._Cuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cuenta.Entity = null;
						previousValue.Perfil.Remove(this);
					}
					this._Cuenta.Entity = value;
					if ((value != null))
					{
						value.Perfil.Add(this);
						this._CuentaID = value.CuentaID;
					}
					else
					{
						this._CuentaID = default(int);
					}
					this.SendPropertyChanged("Cuenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProveedorExterno")]
	public partial class ProveedorExterno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProveedorExternoID;
		
		private int _CuentaID;
		
		private string _Proveedor;
		
		private string _ProveedorUserID;
		
		private string _EmailProveedor;
		
		private System.DateTime _FechaVinculacion;
		
		private EntityRef<Cuenta> _Cuenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProveedorExternoIDChanging(int value);
    partial void OnProveedorExternoIDChanged();
    partial void OnCuentaIDChanging(int value);
    partial void OnCuentaIDChanged();
    partial void OnProveedorChanging(string value);
    partial void OnProveedorChanged();
    partial void OnProveedorUserIDChanging(string value);
    partial void OnProveedorUserIDChanged();
    partial void OnEmailProveedorChanging(string value);
    partial void OnEmailProveedorChanged();
    partial void OnFechaVinculacionChanging(System.DateTime value);
    partial void OnFechaVinculacionChanged();
    #endregion
		
		public ProveedorExterno()
		{
			this._Cuenta = default(EntityRef<Cuenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProveedorExternoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProveedorExternoID
		{
			get
			{
				return this._ProveedorExternoID;
			}
			set
			{
				if ((this._ProveedorExternoID != value))
				{
					this.OnProveedorExternoIDChanging(value);
					this.SendPropertyChanging();
					this._ProveedorExternoID = value;
					this.SendPropertyChanged("ProveedorExternoID");
					this.OnProveedorExternoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaID", DbType="Int NOT NULL")]
		public int CuentaID
		{
			get
			{
				return this._CuentaID;
			}
			set
			{
				if ((this._CuentaID != value))
				{
					if (this._Cuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCuentaIDChanging(value);
					this.SendPropertyChanging();
					this._CuentaID = value;
					this.SendPropertyChanged("CuentaID");
					this.OnCuentaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proveedor", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Proveedor
		{
			get
			{
				return this._Proveedor;
			}
			set
			{
				if ((this._Proveedor != value))
				{
					this.OnProveedorChanging(value);
					this.SendPropertyChanging();
					this._Proveedor = value;
					this.SendPropertyChanged("Proveedor");
					this.OnProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProveedorUserID", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ProveedorUserID
		{
			get
			{
				return this._ProveedorUserID;
			}
			set
			{
				if ((this._ProveedorUserID != value))
				{
					this.OnProveedorUserIDChanging(value);
					this.SendPropertyChanging();
					this._ProveedorUserID = value;
					this.SendPropertyChanged("ProveedorUserID");
					this.OnProveedorUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailProveedor", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string EmailProveedor
		{
			get
			{
				return this._EmailProveedor;
			}
			set
			{
				if ((this._EmailProveedor != value))
				{
					this.OnEmailProveedorChanging(value);
					this.SendPropertyChanging();
					this._EmailProveedor = value;
					this.SendPropertyChanged("EmailProveedor");
					this.OnEmailProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaVinculacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaVinculacion
		{
			get
			{
				return this._FechaVinculacion;
			}
			set
			{
				if ((this._FechaVinculacion != value))
				{
					this.OnFechaVinculacionChanging(value);
					this.SendPropertyChanging();
					this._FechaVinculacion = value;
					this.SendPropertyChanged("FechaVinculacion");
					this.OnFechaVinculacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cuenta_ProveedorExterno", Storage="_Cuenta", ThisKey="CuentaID", OtherKey="CuentaID", IsForeignKey=true)]
		public Cuenta Cuenta
		{
			get
			{
				return this._Cuenta.Entity;
			}
			set
			{
				Cuenta previousValue = this._Cuenta.Entity;
				if (((previousValue != value) 
							|| (this._Cuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cuenta.Entity = null;
						previousValue.ProveedorExterno.Remove(this);
					}
					this._Cuenta.Entity = value;
					if ((value != null))
					{
						value.ProveedorExterno.Add(this);
						this._CuentaID = value.CuentaID;
					}
					else
					{
						this._CuentaID = default(int);
					}
					this.SendPropertyChanged("Cuenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_Cuenta_BuscarResult
	{
		
		private int _CuentaID;
		
		private string _Email;
		
		private byte _Rol;
		
		private byte _Estado;
		
		private System.Nullable<System.DateTime> _UltimoAcceso;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private System.Data.Linq.Binary _FotoPerfil;
		
		public sp_Cuenta_BuscarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaID", DbType="Int NOT NULL")]
		public int CuentaID
		{
			get
			{
				return this._CuentaID;
			}
			set
			{
				if ((this._CuentaID != value))
				{
					this._CuentaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="TinyInt NOT NULL")]
		public byte Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this._Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt NOT NULL")]
		public byte Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimoAcceso", DbType="DateTime")]
		public System.Nullable<System.DateTime> UltimoAcceso
		{
			get
			{
				return this._UltimoAcceso;
			}
			set
			{
				if ((this._UltimoAcceso != value))
				{
					this._UltimoAcceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(100)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(100)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoPerfil", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary FotoPerfil
		{
			get
			{
				return this._FotoPerfil;
			}
			set
			{
				if ((this._FotoPerfil != value))
				{
					this._FotoPerfil = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
