<?xml version="1.0" encoding="utf-8"?><Database Name="colitas_felices_2" Class="ColitasFelicesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sqldatabasecf.database.windows.net;Initial Catalog=colitas_felices_2;User ID=up_colitas_felices;Encrypt=False" SettingsObjectName="capa_datos.Properties.Settings" SettingsPropertyName="colitas_felices_2ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cuenta" Member="Cuenta">
    <Type Name="Cuenta">
      <Column Name="CuentaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GoogleID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Rol" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TokenVerificacion" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="TokenExpiracion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IntentosFallidos" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="BloqueadoHasta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VecesBloqueo" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UltimoAcceso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Cuenta_Perfil" Member="Perfil" ThisKey="CuentaID" OtherKey="CuentaID" Type="Perfil" />
    </Type>
  </Table>
  <Table Name="dbo.Perfil" Member="Perfil">
    <Type Name="Perfil">
      <Column Name="PerfilID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CuentaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrimerNombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoNombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PrimerApellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoApellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cedula" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Ocupacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FotoPerfil" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaActualizacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Cuenta_Perfil" Member="Cuenta" ThisKey="CuentaID" OtherKey="CuentaID" Type="Cuenta" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.SEG_AdminCuenta" Method="SEG_AdminCuenta">
    <Parameter Name="CuentaIDAdmin" Parameter="cuentaIDAdmin" Type="System.Int32" DbType="Int" />
    <Parameter Name="CuentaIDObjetivo" Parameter="cuentaIDObjetivo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="NuevoRol" Parameter="nuevoRol" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="NuevoEstado" Parameter="nuevoEstado" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="Motivo" Parameter="motivo" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Exitoso" Parameter="exitoso" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(300)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SEG_Login" Method="SEG_Login">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="PasswordCorrecto" Parameter="passwordCorrecto" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CuentaID" Parameter="cuentaID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="PasswordHash" Parameter="passwordHash" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Parameter Name="Rol" Parameter="rol" Type="System.Byte" DbType="TinyInt" Direction="InOut" />
    <Parameter Name="PrimerNombre" Parameter="primerNombre" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="PrimerApellido" Parameter="primerApellido" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="FotoPerfil" Parameter="fotoPerfil" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" Direction="InOut" />
    <Parameter Name="Exitoso" Parameter="exitoso" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(300)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SEG_LoginExterno" Method="SEG_LoginExterno">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="ProveedorID" Parameter="proveedorID" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Proveedor" Parameter="proveedor" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PrimerNombre" Parameter="primerNombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PrimerApellido" Parameter="primerApellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FotoUrl" Parameter="fotoUrl" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="CuentaID" Parameter="cuentaID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Rol" Parameter="rol" Type="System.Byte" DbType="TinyInt" Direction="InOut" />
    <Parameter Name="NombreSalida" Parameter="nombreSalida" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="ApellidoSalida" Parameter="apellidoSalida" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="FotoPerfil" Parameter="fotoPerfil" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" Direction="InOut" />
    <Parameter Name="EsNuevo" Parameter="esNuevo" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Exitoso" Parameter="exitoso" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(300)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SEG_LoginResultado" Method="SEG_LoginResultado">
    <Parameter Name="CuentaID" Parameter="cuentaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="LoginExitoso" Parameter="loginExitoso" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Exitoso" Parameter="exitoso" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(300)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SEG_ObtenerDatos" Method="SEG_ObtenerDatos">
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="CuentaID" Parameter="cuentaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Rol" Parameter="rol" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="Estado" Parameter="estado" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="Pagina" Parameter="pagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="PorPagina" Parameter="porPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalRegistros" Parameter="totalRegistros" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="TotalPaginas" Parameter="totalPaginas" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Exitoso" Parameter="exitoso" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(300)" Direction="InOut" />
    <ElementType Name="SEG_ObtenerDatosResult">
      <Column Name="CuentaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Rol" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="GoogleID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TieneGoogle" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IntentosFallidos" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="BloqueadoHasta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VecesBloqueo" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UltimoAcceso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PerfilID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrimerNombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoNombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PrimerApellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoApellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cedula" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Ocupacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FotoPerfil" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaActualizacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SEG_Perfil" Method="SEG_Perfil">
    <Parameter Name="CuentaID" Parameter="cuentaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="PrimerNombre" Parameter="primerNombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SegundoNombre" Parameter="segundoNombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PrimerApellido" Parameter="primerApellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SegundoApellido" Parameter="segundoApellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="FechaNacimiento" Parameter="fechaNacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Ocupacion" Parameter="ocupacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FotoPerfil" Parameter="fotoPerfil" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" Direction="InOut" />
    <Parameter Name="Rol" Parameter="rol" Type="System.Byte" DbType="TinyInt" Direction="InOut" />
    <Parameter Name="PrimerNombreOut" Parameter="primerNombreOut" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="SegundoNombreOut" Parameter="segundoNombreOut" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="PrimerApellidoOut" Parameter="primerApellidoOut" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="SegundoApellidoOut" Parameter="segundoApellidoOut" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="CedulaOut" Parameter="cedulaOut" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Parameter Name="TelefonoOut" Parameter="telefonoOut" Type="System.String" DbType="VarChar(15)" Direction="InOut" />
    <Parameter Name="DireccionOut" Parameter="direccionOut" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="FechaNacimientoOut" Parameter="fechaNacimientoOut" Type="System.DateTime" DbType="Date" Direction="InOut" />
    <Parameter Name="OcupacionOut" Parameter="ocupacionOut" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="FotoPerfilOut" Parameter="fotoPerfilOut" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" Direction="InOut" />
    <Parameter Name="TieneGoogle" Parameter="tieneGoogle" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="FechaRegistro" Parameter="fechaRegistro" Type="System.DateTime" DbType="DateTime" Direction="InOut" />
    <Parameter Name="Exitoso" Parameter="exitoso" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(300)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SEG_RecuperarPassword" Method="SEG_RecuperarPassword">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Codigo" Parameter="codigo" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="NuevoPasswordHash" Parameter="nuevoPasswordHash" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CuentaID" Parameter="cuentaID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Token" Parameter="token" Type="System.String" DbType="VarChar(6)" Direction="InOut" />
    <Parameter Name="Exitoso" Parameter="exitoso" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(300)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SEG_Registrar" Method="SEG_Registrar">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="PasswordHash" Parameter="passwordHash" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="PrimerNombre" Parameter="primerNombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PrimerApellido" Parameter="primerApellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CuentaID" Parameter="cuentaID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Token" Parameter="token" Type="System.String" DbType="VarChar(6)" Direction="InOut" />
    <Parameter Name="Exitoso" Parameter="exitoso" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(300)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SEG_VerificarCodigo" Method="SEG_VerificarCodigo">
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Codigo" Parameter="codigo" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="Token" Parameter="token" Type="System.String" DbType="VarChar(6)" Direction="InOut" />
    <Parameter Name="Exitoso" Parameter="exitoso" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(300)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>