<?xml version="1.0" encoding="utf-8"?><Database Name="DB_ColitasFelices" Class="ColitasFelicesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=DB_ColitasFelices;Integrated Security=True;Encrypt=False" SettingsObjectName="capa_datos.Properties.Settings" SettingsPropertyName="DB_ColitasFelicesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.cuenta" Member="cuenta">
    <Type Name="cuenta">
      <Column Name="CuentaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GoogleID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RolID" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IntentosFallidos" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="BloqueadoHasta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VecesBloqueo" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UltimoAcceso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="cuenta_cuenta_permiso" Member="cuenta_permiso" ThisKey="CuentaID" OtherKey="AsignadoPor" Type="cuenta_permiso" />
      <Association Name="cuenta_cuenta_permiso1" Member="cuenta_permiso1" ThisKey="CuentaID" OtherKey="CuentaID" Type="cuenta_permiso" />
      <Association Name="cuenta_recuperacion_password" Member="recuperacion_password" ThisKey="CuentaID" OtherKey="CuentaID" Type="recuperacion_password" />
      <Association Name="cuenta_rel_perfil_documento" Member="rel_perfil_documento" ThisKey="CuentaID" OtherKey="RevisadoPor" Type="rel_perfil_documento" />
      <Association Name="cuenta_perfil" Member="perfil" ThisKey="CuentaID" OtherKey="CuentaID" Type="perfil" />
      <Association Name="rol_cuenta" Member="rol" ThisKey="RolID" OtherKey="RolID" Type="rol" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.cuenta_permiso" Member="cuenta_permiso">
    <Type Name="cuenta_permiso">
      <Column Name="CuentaID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PermisoID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FechaAsignacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AsignadoPor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="cuenta_cuenta_permiso" Member="cuenta" ThisKey="AsignadoPor" OtherKey="CuentaID" Type="cuenta" IsForeignKey="true" />
      <Association Name="cuenta_cuenta_permiso1" Member="cuenta1" ThisKey="CuentaID" OtherKey="CuentaID" Type="cuenta" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="permiso_cuenta_permiso" Member="permiso" ThisKey="PermisoID" OtherKey="PermisoID" Type="permiso" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.documento_perfil" Member="documento_perfil">
    <Type Name="documento_perfil">
      <Column Name="DocumentoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoDocumentoID" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="NombreArchivo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BlobUrl" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ContentType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TamanoBytes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaSubida" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="documento_perfil_rel_perfil_documento" Member="rel_perfil_documento" ThisKey="DocumentoID" OtherKey="DocumentoID" Type="rel_perfil_documento" />
      <Association Name="tipo_documento_documento_perfil" Member="tipo_documento" ThisKey="TipoDocumentoID" OtherKey="TipoDocumentoID" Type="tipo_documento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.permiso" Member="permiso">
    <Type Name="permiso">
      <Column Name="PermisoID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Codigo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Modulo" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="permiso_cuenta_permiso" Member="cuenta_permiso" ThisKey="PermisoID" OtherKey="PermisoID" Type="cuenta_permiso" />
    </Type>
  </Table>
  <Table Name="dbo.recuperacion_password" Member="recuperacion_password">
    <Type Name="recuperacion_password">
      <Column Name="RecuperacionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CuentaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TokenExpiracion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Usado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FechaUso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="cuenta_recuperacion_password" Member="cuenta" ThisKey="CuentaID" OtherKey="CuentaID" Type="cuenta" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.registro_temporal" Member="registro_temporal">
    <Type Name="registro_temporal">
      <Column Name="RegistroID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PrimerNombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoNombre" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PrimerApellido" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoApellido" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CodigoVerificacion" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoExpiracion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Verificado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Intentos" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Reenvios" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="UltimoReenvio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.rel_perfil_documento" Member="rel_perfil_documento">
    <Type Name="rel_perfil_documento">
      <Column Name="PerfilID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DocumentoID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Estado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="MotivoRechazo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FechaRevision" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RevisadoPor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="documento_perfil_rel_perfil_documento" Member="documento_perfil" ThisKey="DocumentoID" OtherKey="DocumentoID" Type="documento_perfil" IsForeignKey="true" />
      <Association Name="cuenta_rel_perfil_documento" Member="cuenta" ThisKey="RevisadoPor" OtherKey="CuentaID" Type="cuenta" IsForeignKey="true" />
      <Association Name="perfil_rel_perfil_documento" Member="perfil" ThisKey="PerfilID" OtherKey="PerfilID" Type="perfil" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.rol" Member="rol">
    <Type Name="rol">
      <Column Name="RolID" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="rol_cuenta" Member="cuenta" ThisKey="RolID" OtherKey="RolID" Type="cuenta" />
    </Type>
  </Table>
  <Table Name="dbo.tipo_documento" Member="tipo_documento">
    <Type Name="tipo_documento">
      <Column Name="TipoDocumentoID" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Requerido" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tipo_documento_documento_perfil" Member="documento_perfil" ThisKey="TipoDocumentoID" OtherKey="TipoDocumentoID" Type="documento_perfil" />
    </Type>
  </Table>
  <Table Name="dbo.tipo_identificacion" Member="tipo_identificacion">
    <Type Name="tipo_identificacion">
      <Column Name="TipoIdentificacionID" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Formato" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LongitudMin" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="LongitudMax" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tipo_identificacion_perfil" Member="perfil" ThisKey="TipoIdentificacionID" OtherKey="TipoIdentificacionID" Type="perfil" />
    </Type>
  </Table>
  <Table Name="dbo.perfil" Member="perfil">
    <Type Name="perfil">
      <Column Name="PerfilID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CuentaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrimerNombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoNombre" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PrimerApellido" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoApellido" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="TipoIdentificacionID" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Genero" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TelefonoPrincipal" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TelefonoAlternativo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaActualizacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="perfil_rel_perfil_documento" Member="rel_perfil_documento" ThisKey="PerfilID" OtherKey="PerfilID" Type="rel_perfil_documento" />
      <Association Name="cuenta_perfil" Member="cuenta" ThisKey="CuentaID" OtherKey="CuentaID" Type="cuenta" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="tipo_identificacion_perfil" Member="tipo_identificacion" ThisKey="TipoIdentificacionID" OtherKey="TipoIdentificacionID" Type="tipo_identificacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.SEG_ConfirmarRegistro" Method="SEG_ConfirmarRegistro">
    <Parameter Name="RegistroID" Parameter="registroID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CuentaID" Parameter="cuentaID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>